"""Fresh migration with current schema

Revision ID: 9eaa46020718
Revises:
Create Date: 2026-04-08 18:00:18.982585

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9eaa46020718"
down_revision = None
branch_labels = None
depends_on = None


def _has_table(inspector, table_name):
    return table_name in inspector.get_table_names()


def _has_column(inspector, table_name, column_name):
    return column_name in {column["name"] for column in inspector.get_columns(table_name)}


def _has_index(inspector, table_name, index_name):
    return index_name in {index["name"] for index in inspector.get_indexes(table_name)}


def _has_foreign_key(inspector, table_name, constraint_name):
    return constraint_name in {
        foreign_key["name"] for foreign_key in inspector.get_foreign_keys(table_name)
    }


def _has_unique_constraint(inspector, table_name, column_names):
    expected = tuple(column_names)
    for constraint in inspector.get_unique_constraints(table_name):
        if tuple(constraint.get("column_names") or ()) == expected:
            return True
    return False


def _create_users_table():
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.UniqueConstraint("username", name="uq_users_username"),
    )


def _create_projects_table():
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("short_description", sa.String(length=255), nullable=True),
        sa.Column("technologies", sa.String(length=255), nullable=True),
        sa.Column("project_url", sa.String(length=255), nullable=True),
        sa.Column("github_url", sa.String(length=255), nullable=True),
        sa.Column("featured_image", sa.String(length=255), nullable=True),
        sa.Column("images", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("featured", sa.Boolean(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )


def _create_contacts_table():
    op.create_table(
        "contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("service", sa.String(length=50), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if _has_table(inspector, "contact_messages"):
        op.drop_table("contact_messages")

    users_created = not _has_table(inspector, "users")
    if users_created:
        _create_users_table()

    projects_created = not _has_table(inspector, "projects")
    if projects_created:
        _create_projects_table()

    if not _has_table(inspector, "contacts"):
        _create_contacts_table()

    inspector = sa.inspect(bind)

    if _has_table(inspector, "projects") and not projects_created:
        with op.batch_alter_table("projects", schema=None) as batch_op:
            if _has_column(inspector, "projects", "title"):
                batch_op.alter_column(
                    "title",
                    existing_type=sa.VARCHAR(length=200),
                    type_=sa.String(length=100),
                    existing_nullable=False,
                )
            if _has_column(inspector, "projects", "short_description"):
                batch_op.alter_column(
                    "short_description",
                    existing_type=sa.VARCHAR(length=300),
                    type_=sa.String(length=255),
                    existing_nullable=True,
                )
            if _has_column(inspector, "projects", "technologies"):
                batch_op.alter_column(
                    "technologies",
                    existing_type=sa.VARCHAR(length=300),
                    type_=sa.String(length=255),
                    existing_nullable=True,
                )
            if _has_column(inspector, "projects", "project_url"):
                batch_op.alter_column(
                    "project_url",
                    existing_type=sa.VARCHAR(length=500),
                    type_=sa.String(length=255),
                    existing_nullable=True,
                )
            if _has_column(inspector, "projects", "github_url"):
                batch_op.alter_column(
                    "github_url",
                    existing_type=sa.VARCHAR(length=500),
                    type_=sa.String(length=255),
                    existing_nullable=True,
                )
            if _has_column(inspector, "projects", "featured_image"):
                batch_op.alter_column(
                    "featured_image",
                    existing_type=sa.VARCHAR(length=500),
                    type_=sa.String(length=255),
                    existing_nullable=True,
                )
            if _has_column(inspector, "projects", "images"):
                batch_op.alter_column(
                    "images",
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    type_=sa.Text(),
                    existing_nullable=True,
                )
            if _has_column(inspector, "projects", "status"):
                batch_op.alter_column(
                    "status",
                    existing_type=sa.VARCHAR(length=20),
                    type_=sa.String(length=50),
                    existing_nullable=True,
                )
            if _has_column(inspector, "projects", "user_id"):
                batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)
            if _has_foreign_key(inspector, "projects", "projects_user_id_fkey"):
                batch_op.drop_constraint("projects_user_id_fkey", type_="foreignkey")

    if _has_table(inspector, "users") and not users_created:
        with op.batch_alter_table("users", schema=None) as batch_op:
            if not _has_column(inspector, "users", "last_login"):
                batch_op.add_column(sa.Column("last_login", sa.DateTime(), nullable=True))
            if _has_column(inspector, "users", "username"):
                batch_op.alter_column(
                    "username",
                    existing_type=sa.VARCHAR(length=64),
                    type_=sa.String(length=80),
                    existing_nullable=False,
                )
            if _has_column(inspector, "users", "password_hash"):
                batch_op.alter_column(
                    "password_hash",
                    existing_type=sa.VARCHAR(length=128),
                    type_=sa.String(length=255),
                    nullable=False,
                )
            if _has_index(inspector, "users", "ix_users_email"):
                batch_op.drop_index("ix_users_email")
            if _has_index(inspector, "users", "ix_users_username"):
                batch_op.drop_index("ix_users_username")
            if not _has_unique_constraint(inspector, "users", ["username"]):
                batch_op.create_unique_constraint("uq_users_username", ["username"])
            if not _has_unique_constraint(inspector, "users", ["email"]):
                batch_op.create_unique_constraint("uq_users_email", ["email"])
            if _has_column(inspector, "users", "updated_at"):
                batch_op.drop_column("updated_at")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
        )
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.create_index("ix_users_username", ["username"], unique=False)
        batch_op.create_index("ix_users_email", ["email"], unique=False)
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=128),
            nullable=True,
        )
        batch_op.alter_column(
            "username",
            existing_type=sa.String(length=80),
            type_=sa.VARCHAR(length=64),
            existing_nullable=False,
        )
        batch_op.drop_column("last_login")

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_foreign_key("projects_user_id_fkey", "users", ["user_id"], ["id"])
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "status",
            existing_type=sa.String(length=50),
            type_=sa.VARCHAR(length=20),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "images",
            existing_type=sa.Text(),
            type_=postgresql.JSON(astext_type=sa.Text()),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "featured_image",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=500),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "github_url",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=500),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "project_url",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=500),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "technologies",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=300),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "short_description",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=300),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "title",
            existing_type=sa.String(length=100),
            type_=sa.VARCHAR(length=200),
            existing_nullable=False,
        )

    op.create_table(
        "contact_messages",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=120), autoincrement=False, nullable=False),
        sa.Column("subject", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("ip_address", sa.VARCHAR(length=45), autoincrement=False, nullable=True),
        sa.Column("user_agent", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("NEW", "READ", "REPLIED", "ARCHIVED", name="messagestatus"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("replied_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="contact_messages_pkey"),
    )
    # ### end Alembic commands ###
